### ISSUE TITLE
please add install instructions ... all I can see is json files

### ISSUE THREAD

**Issue by grosser** [vas3k/btt-touchbar-presets#5]
maybe even an installer if that's possible ...

**Comment by travisperson** [comment]
After installing BetterTouchTool (https://www.boastr.net/), you can import / export configurations from the  **Manage Presets** button.

<img width="773" alt="screen shot 2018-04-04 at 9 26 24 pm" src="https://user-images.githubusercontent.com/165274/38347208-e4969c22-384e-11e8-9ec1-8d665a9bc010.png">

**Comment by grosser** [comment]
I found that, but having that in the readme would be great :)

**Comment by travisperson** [comment]
I agree, but I figured others might come to the issues and find it helpful.

**Comment by grosser** [comment]
thx!

**Comment by plingampally** [comment]
I'm getting "Error: Sorry, the preset couldn't be imported as it seems to be in the wrong format." when i import any of the JSON files. I'm using the latest version of BTT.

**Comment by vas3k** [comment]
@travisperson Thank you, I added your screenshot to the readme. I think this is enough to understand how to install presets :)
